language: node_js

node_js: 
  - "8"

branch:
  only: 
    - master

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn

script:
  - yarn test && yarn docs:build

deploy:
  provider: pages
  skip-cleanup: true
  gh-token: 6ed69005d9f265fac5a6217018d57cfe191b2f51
  local-dir: ./docs/.vuepress/dist/
  target-branch: gh-pages
  verbose: true
  on:
    branch: master