language: node_js

node_js: 
  - "8"

branch:
  only: 
    - master

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn

script:
  - yarn cover

# after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"